# Generated by Django 3.0.14 on 2023-01-15 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20230116_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 0, 18, 8, 729072), verbose_name='Дата заказа'),
        ),
    ]
