# Generated by Django 3.0.14 on 2023-01-15 22:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20230116_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 0, 44, 25, 239633), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='table',
            name='length',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Введите длину стола(от 1 до 100)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='width',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Введите ширину стола(от 1 до 100)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='x',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Введите положение стола по x(от 1 до 100)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='y',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Введите положение по y(от 1 до 100)'),
        ),
    ]
